services:
  api:
    build: ./app
    container_name: repnet_api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "127.0.0.1:8000:8000"

  redis:
    image: redis:7-alpine
    container_name: repnet_redis
    restart: unless-stopped